baseURL = "https://soldaini.net/"
languageCode = "en-us"
title = "Luca Soldaini"
theme = "researcher"
enableEmoji = true
math = false  # enable KaTeX (https://katex.org/) globally

[params]
  author = "Luca Soldaini"
  description = "Luca Soldaini is an Applied Scientist at Amazon Alexa Search."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  keywords = "luca, soldaini, personal, homepage, georgetown, university, amazon, alexa, search"
  google_site_validation = "0w6io-9zaQ-219xst17NcKH0e3I5FzbrkNcr8R7vL4U"
  msvalidate_01 = "6A330A58006408660C4D6B81B04E8740"
  google_analytics = "UA-72750578-2"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Facts"
    url = "/facts"
    weight = 2

  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 3

  [[menu.main]]
    name = "CV"
    url = "/cv.pdf"
    weight = 4


[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
