baseURL = "https://soldaini.net/"
languageCode = "en-us"
title = "Luca Soldaini"
theme = "soldaini"
enableEmoji = true
math = false  # enable KaTeX (https://katex.org/) globally
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[pagination]
  pagerSize = 8

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "Luca Soldaini"
  lang = "en"
  description = "Personal website of Luca Soldaini; lead research scientist at the Allen Institute for AI (Ai2)."
  favicon = "2nd-gen-favicon/composed/light/favicon.ico"  # path to a .ico to use as favicon
  keywords = "luca, soldaini, personal, homepage, question answering, natural language processing, information retrieval, georgetown, university, amazon, alexa, search, ai, machine learning, natural language processing, Ai2, allen institute for ai, allen ai, semantic scholar, queer in ai"
  google_site_validation = "0w6io-9zaQ-219xst17NcKH0e3I5FzbrkNcr8R7vL4U"
  msvalidate_01 = "6A330A58006408660C4D6B81B04E8740"

[permalinks]
  "/" = "/:filename"

[menu]

  [[menu.main]]
    name = "Misc"
    url = "/misc"
    weight = 1

  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
